<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8jqjg2x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8jqjg2x/appProdProjectContainer.php') {
    touch(__DIR__.'/Container8jqjg2x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container8jqjg2x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container8jqjg2x\appProdProjectContainer([
    'container.build_hash' => '8jqjg2x',
    'container.build_id' => '322a5978',
    'container.build_time' => 1669646427,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8jqjg2x');
