<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSm3nms5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSm3nms5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSm3nms5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSm3nms5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSm3nms5\appProdProjectContainer([
    'container.build_hash' => 'Sm3nms5',
    'container.build_id' => 'b2038b68',
    'container.build_time' => 1670797534,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSm3nms5');
